---
name: Build
on: workflow_dispatch

env:
  REGISTRY_IMAGE: kirillzak/rudderstack-config-generator

jobs:
  test:
    name: Test build of image with RudderStack config generator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build an image
        uses: docker/build-push-action@v6
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true
          push: false
          tags: |
            kirillzak/rudderstack-config-generator:latest
            ghcr.io/${{ github.repository }}:latest
